[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd font"
style = "Regular"

[window]

dimensions = { columns = 92, lines = 28}
opacity = 0.8
resize_increments = false

# Default colors
[colors.primary]
background = '#1e1e1e'
foreground = '#cccccc'


# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cd3131'
green   = '#0dbc79'
yellow  = '#e5e510'
blue    = '#2472c8'
magenta = '#bc3fbc'
cyan    = '#11a8cd'
white   = '#e5e5e5'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#f14c4c'
green   = '#23d18b'
yellow  = '#f5f543'
blue    = '#3b8eea'
magenta = '#d670d6'
cyan    = '#29b8db'
white   = '#e5e5e5'

# cursor #ffffff
# selection_background #3a3d41
# selection_foreground #e0e0e0

[cursor]

style = { shape = "Beam", blinking = "On" }
blink_interval = 500
thickness = 0.2

[mouse]

hide_when_typing = true

[terminal]
shell = "nu"

